name = "langchain4a"
description = "A LangChain-inspired library for LLM-powered Ada apps"
version = "0.1.0"

authors = ["Ali Ahmadnejad"]
maintainers = ["Ali Ahmadnejad <sa.ahmadnejad@gmail.com>"]
licenses = "MIT"
tags = ["llm", "ai", "langchain", "chat", "openai"]
website = "https://github.com/saahmadnejad/langchain4a"

executables = []

[[depends-on]]
aunit = "^25.0.0"
aws = "^24.0.0"
